### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by LewBr** [NL-4-DEVS/PushInventory#4]
Notice: Undefined offset: 1 in C:\Users\Leo\Desktop\Server\plugins\PushInventory-master\src\driesboy\Main.php on line 137

Notice: Undefined variable: f in C:\Users\Leo\Desktop\Server\plugins\PushInventory-master\src\driesboy\Main.php on line 66

Warning: Invalid argument supplied for foreach() in C:\Users\Leo\Desktop\Server\plugins\PushInventory-master\src\driesboy\Main.php on line 66

Notice: Undefined offset: 1 in C:\Users\Leo\Desktop\Server\plugins\PushInventory-master\src\driesboy\Main.php on line 137

Notice: Undefined variable: f in C:\Users\Leo\Desktop\Server\plugins\PushInventory-master\src\driesboy\Main.php on line 66

Warning: Invalid argument supplied for foreach() in C:\Users\Leo\Desktop\Server\plugins\PushInventory-master\src\driesboy\Main.php on line 66

**Comment by Driesboy** [comment]
fixed
