### ISSUE TITLE
And Now.... again..

### ISSUE THREAD

**Issue by LewBr** [NL-4-DEVS/PushInventory#7]
And now.. plugin work's at the pocketmine, but does't work he function! and does't comes new Error Messages, did you make an upload or test? because that's not a error, think.. just breaked function..

**Comment by LewBr** [comment]
i click at the sword, and doesnt work the commands :/

**Comment by LewBr** [comment]
(sorry english)

**Comment by Driesboy** [comment]
it work for genisys

**Comment by Driesboy** [comment]
do you got the swords?

**Comment by Driesboy** [comment]
whats your lobby map name?

**Comment by LewBr** [comment]
world lol

**Comment by LewBr** [comment]
for me, doesnt work :/

**Comment by Driesboy** [comment]
i will make a priv version for you

**Comment by LewBr** [comment]
can you send me at twitter?

**Comment by Driesboy** [comment]
yes
